export type FeeStatus = 'Paid' | 'Partial' | 'Pending' | 'Overdue';
export type School = 'Rajiv Gandhi Polytechnic' | 'Rajiv Gandhi ITI' | 'GSS Diploma College';

export interface FeeRecord {
  id: string;
  receiptNo: string;
  studentId: string;
  rollNo: string;
  studentName: string;
  school: School;
  course: string;
  semester: number;
  annualFee: number;
  discount: number;
  paidAmount: number;
  paymentDate: string;
  paymentMode: 'Cash' | 'Online' | 'DD' | 'Cheque';
  remarks: string;
  status: FeeStatus;
  academicYear: string;
}

export const RECEIPT_PREFIX: Record<School, string> = {
  'Rajiv Gandhi Polytechnic': 'RGP-REC',
  'Rajiv Gandhi ITI': 'ITI-REC',
  'GSS Diploma College': 'GSS-REC',
};

export const mockFeeRecords: FeeRecord[] = [
  {
    id: 'fee-3001',
    receiptNo: 'RGP-REC-2026-0217',
    studentId: 'std-2001',
    rollNo: 'RGP-2026-001',
    studentName: 'Priya Sharma',
    school: 'Rajiv Gandhi Polytechnic',
    course: 'Civil Engineering',
    semester: 2,
    annualFee: 20000,
    discount: 0,
    paidAmount: 20000,
    paymentDate: '17/07/2026',
    paymentMode: 'Online',
    remarks: 'Full payment',
    status: 'Paid',
    academicYear: '2026-27',
  },
  {
    id: 'fee-3002',
    receiptNo: 'RGP-REC-2026-0216',
    studentId: 'std-2002',
    rollNo: 'RGP-2026-002',
    studentName: 'Aakash Patel',
    school: 'Rajiv Gandhi Polytechnic',
    course: 'Mechanical Engineering',
    semester: 4,
    annualFee: 20000,
    discount: 0,
    paidAmount: 10000,
    paymentDate: '15/07/2026',
    paymentMode: 'Cash',
    remarks: 'First instalment',
    status: 'Partial',
    academicYear: '2026-27',
  },
  {
    id: 'fee-3003',
    receiptNo: 'RGP-REC-2026-0215',
    studentId: 'std-2003',
    rollNo: 'RGP-2026-003',
    studentName: 'Neha Gupta',
    school: 'Rajiv Gandhi Polytechnic',
    course: 'Electrical Engineering',
    semester: 1,
    annualFee: 20000,
    discount: 0,
    paidAmount: 0,
    paymentDate: '—',
    paymentMode: 'Cash',
    remarks: '',
    status: 'Pending',
    academicYear: '2026-27',
  },
  {
    id: 'fee-3004',
    receiptNo: 'RGP-REC-2026-0214',
    studentId: 'std-2004',
    rollNo: 'RGP-2026-004',
    studentName: 'Vikram Singh Yadav',
    school: 'Rajiv Gandhi Polytechnic',
    course: 'Civil Engineering',
    semester: 3,
    annualFee: 25000,
    discount: 2000,
    paidAmount: 25000,
    paymentDate: '10/07/2026',
    paymentMode: 'DD',
    remarks: 'Lateral entry, ₹2000 merit discount',
    status: 'Paid',
    academicYear: '2026-27',
  },
  {
    id: 'fee-3005',
    receiptNo: 'ITI-REC-2026-0079',
    studentId: 'std-2005',
    rollNo: 'ITI-2026-001',
    studentName: 'Ramu Kevat',
    school: 'Rajiv Gandhi ITI',
    course: 'Fitter',
    semester: 2,
    annualFee: 15000,
    discount: 1500,
    paidAmount: 15000,
    paymentDate: '12/07/2026',
    paymentMode: 'Online',
    remarks: 'SC category scholarship discount',
    status: 'Paid',
    academicYear: '2026-27',
  },
  {
    id: 'fee-3006',
    receiptNo: 'ITI-REC-2026-0078',
    studentId: 'std-2006',
    rollNo: 'ITI-2026-002',
    studentName: 'Anita Maurya',
    school: 'Rajiv Gandhi ITI',
    course: 'Electrician',
    semester: 1,
    annualFee: 15000,
    discount: 0,
    paidAmount: 0,
    paymentDate: '—',
    paymentMode: 'Cash',
    remarks: 'Overdue since April 2026',
    status: 'Overdue',
    academicYear: '2026-27',
  },
  {
    id: 'fee-3007',
    receiptNo: 'ITI-REC-2026-0077',
    studentId: 'std-2007',
    rollNo: 'ITI-2026-003',
    studentName: 'Santosh Kumar',
    school: 'Rajiv Gandhi ITI',
    course: 'Welder',
    semester: 3,
    annualFee: 15000,
    discount: 500,
    paidAmount: 8000,
    paymentDate: '05/07/2026',
    paymentMode: 'Cash',
    remarks: 'Partial — balance due',
    status: 'Partial',
    academicYear: '2026-27',
  },
  {
    id: 'fee-3008',
    receiptNo: 'ITI-REC-2026-0076',
    studentId: 'std-2008',
    rollNo: 'ITI-2026-004',
    studentName: 'Pooja Bind',
    school: 'Rajiv Gandhi ITI',
    course: 'Fitter',
    semester: 4,
    annualFee: 15000,
    discount: 0,
    paidAmount: 15000,
    paymentDate: '01/07/2026',
    paymentMode: 'Cheque',
    remarks: 'Full payment by cheque',
    status: 'Paid',
    academicYear: '2026-27',
  },
  {
    id: 'fee-3009',
    receiptNo: 'GSS-REC-2026-0040',
    studentId: 'std-2009',
    rollNo: 'GSS-2026-001',
    studentName: 'Sunita Devi',
    school: 'GSS Diploma College',
    course: 'Diploma in Special Education (HI)',
    semester: 2,
    annualFee: 40000,
    discount: 5000,
    paidAmount: 40000,
    paymentDate: '08/07/2026',
    paymentMode: 'Online',
    remarks: 'Full fee, ₹5000 govt. scholarship adjusted',
    status: 'Paid',
    academicYear: '2026-27',
  },
  {
    id: 'fee-3010',
    receiptNo: 'GSS-REC-2026-0039',
    studentId: 'std-2010',
    rollNo: 'GSS-2026-002',
    studentName: 'Manoj Tiwari',
    school: 'GSS Diploma College',
    course: 'Diploma in Special Education (MR)',
    semester: 1,
    annualFee: 40000,
    discount: 0,
    paidAmount: 0,
    paymentDate: '—',
    paymentMode: 'Cash',
    remarks: '',
    status: 'Pending',
    academicYear: '2026-27',
  },
  {
    id: 'fee-3011',
    receiptNo: 'RGP-REC-2026-0213',
    studentId: 'std-2011',
    rollNo: 'RGP-2026-005',
    studentName: 'Deepak Rajbhar',
    school: 'Rajiv Gandhi Polytechnic',
    course: 'Mechanical Engineering',
    semester: 5,
    annualFee: 20000,
    discount: 0,
    paidAmount: 5000,
    paymentDate: '20/04/2026',
    paymentMode: 'Cash',
    remarks: 'Overdue — last payment April 2026',
    status: 'Overdue',
    academicYear: '2026-27',
  },
  {
    id: 'fee-3012',
    receiptNo: 'ITI-REC-2026-0075',
    studentId: 'std-2012',
    rollNo: 'ITI-2026-005',
    studentName: 'Kavita Chauhan',
    school: 'Rajiv Gandhi ITI',
    course: 'Electrician',
    semester: 2,
    annualFee: 15000,
    discount: 0,
    paidAmount: 15000,
    paymentDate: '14/07/2026',
    paymentMode: 'Online',
    remarks: 'Full payment online',
    status: 'Paid',
    academicYear: '2026-27',
  },
];