export type FeeStatus = 'Paid' | 'Partial' | 'Pending' | 'Overdue';
export type School = 'Rajiv Gandhi Polytechnic' | 'Rajiv Gandhi ITI' | 'GSS Diploma College';

export interface Student {
  id: string;
  rollNo: string;
  name: string;
  school: School;
  course: string;
  semester: number;
  lateralEntry: boolean;
  admissionYear: string;
  dob: string;
  gender: 'Male' | 'Female' | 'Other';
  guardianName: string;
  phone: string;
  address: string;
  feeStatus: FeeStatus;
  totalFees: number;
  paidFees: number;
  category: 'General' | 'OBC' | 'SC' | 'ST';
  aadhar: string;
}

export const SCHOOL_COURSES: Record<School, string[]> = {
  'Rajiv Gandhi Polytechnic': [
    'Civil Engineering',
    'Mechanical Engineering',
    'Electrical Engineering',
  ],
  'Rajiv Gandhi ITI': ['Fitter', 'Electrician', 'Welder'],
  'GSS Diploma College': [
    'Diploma in Special Education (HI)',
    'Diploma in Special Education (MR)',
  ],
};

export const SCHOOL_FEE: Record<School, { regular: number; lateral: number }> = {
  'Rajiv Gandhi Polytechnic': { regular: 20000, lateral: 25000 },
  'Rajiv Gandhi ITI': { regular: 15000, lateral: 15000 },
  'GSS Diploma College': { regular: 40000, lateral: 40000 },
};

export const mockStudents: Student[] = [
  {
    id: 'std-2001',
    rollNo: 'RGP-2026-001',
    name: 'Priya Sharma',
    school: 'Rajiv Gandhi Polytechnic',
    course: 'Civil Engineering',
    semester: 2,
    lateralEntry: false,
    admissionYear: '2025',
    dob: '12/03/2005',
    gender: 'Female',
    guardianName: 'Ramesh Sharma',
    phone: '9876543210',
    address: 'Village Rampur, Dist. Varanasi, UP',
    feeStatus: 'Paid',
    totalFees: 20000,
    paidFees: 20000,
    category: 'General',
    aadhar: '2345 6789 0123',
  },
  {
    id: 'std-2002',
    rollNo: 'RGP-2026-002',
    name: 'Aakash Patel',
    school: 'Rajiv Gandhi Polytechnic',
    course: 'Mechanical Engineering',
    semester: 4,
    lateralEntry: false,
    admissionYear: '2024',
    dob: '07/08/2004',
    gender: 'Male',
    guardianName: 'Suresh Patel',
    phone: '9823456780',
    address: 'Mohalla Shivpuri, Mirzapur, UP',
    feeStatus: 'Partial',
    totalFees: 20000,
    paidFees: 10000,
    category: 'OBC',
    aadhar: '3456 7890 1234',
  },
  {
    id: 'std-2003',
    rollNo: 'RGP-2026-003',
    name: 'Neha Gupta',
    school: 'Rajiv Gandhi Polytechnic',
    course: 'Electrical Engineering',
    semester: 1,
    lateralEntry: false,
    admissionYear: '2026',
    dob: '22/11/2007',
    gender: 'Female',
    guardianName: 'Dinesh Gupta',
    phone: '9765432109',
    address: 'Nagar Panchayat, Bhadohi, UP',
    feeStatus: 'Pending',
    totalFees: 20000,
    paidFees: 0,
    category: 'General',
    aadhar: '4567 8901 2345',
  },
  {
    id: 'std-2004',
    rollNo: 'RGP-2026-004',
    name: 'Vikram Singh Yadav',
    school: 'Rajiv Gandhi Polytechnic',
    course: 'Civil Engineering',
    semester: 3,
    lateralEntry: true,
    admissionYear: '2025',
    dob: '15/06/2003',
    gender: 'Male',
    guardianName: 'Hariom Yadav',
    phone: '9654321098',
    address: 'Village Chakia, Chandauli, UP',
    feeStatus: 'Paid',
    totalFees: 25000,
    paidFees: 25000,
    category: 'OBC',
    aadhar: '5678 9012 3456',
  },
  {
    id: 'std-2005',
    rollNo: 'ITI-2026-001',
    name: 'Ramu Kevat',
    school: 'Rajiv Gandhi ITI',
    course: 'Fitter',
    semester: 2,
    lateralEntry: false,
    admissionYear: '2025',
    dob: '03/01/2006',
    gender: 'Male',
    guardianName: 'Shivlal Kevat',
    phone: '9543210987',
    address: 'Gram Sabha Kevat Tola, Ghazipur, UP',
    feeStatus: 'Paid',
    totalFees: 15000,
    paidFees: 15000,
    category: 'SC',
    aadhar: '6789 0123 4567',
  },
  {
    id: 'std-2006',
    rollNo: 'ITI-2026-002',
    name: 'Anita Maurya',
    school: 'Rajiv Gandhi ITI',
    course: 'Electrician',
    semester: 1,
    lateralEntry: false,
    admissionYear: '2026',
    dob: '18/09/2007',
    gender: 'Female',
    guardianName: 'Jagdish Maurya',
    phone: '9432109876',
    address: 'Mohalla Umarpur, Azamgarh, UP',
    feeStatus: 'Overdue',
    totalFees: 15000,
    paidFees: 0,
    category: 'OBC',
    aadhar: '7890 1234 5678',
  },
  {
    id: 'std-2007',
    rollNo: 'ITI-2026-003',
    name: 'Santosh Kumar',
    school: 'Rajiv Gandhi ITI',
    course: 'Welder',
    semester: 3,
    lateralEntry: false,
    admissionYear: '2025',
    dob: '27/04/2005',
    gender: 'Male',
    guardianName: 'Lalmani Kumar',
    phone: '9321098765',
    address: 'Village Sarai, Jaunpur, UP',
    feeStatus: 'Partial',
    totalFees: 15000,
    paidFees: 8000,
    category: 'ST',
    aadhar: '8901 2345 6789',
  },
  {
    id: 'std-2008',
    rollNo: 'ITI-2026-004',
    name: 'Pooja Bind',
    school: 'Rajiv Gandhi ITI',
    course: 'Fitter',
    semester: 4,
    lateralEntry: false,
    admissionYear: '2024',
    dob: '09/12/2004',
    gender: 'Female',
    guardianName: 'Ramkhelawan Bind',
    phone: '9210987654',
    address: 'Nai Basti, Allahabad, UP',
    feeStatus: 'Paid',
    totalFees: 15000,
    paidFees: 15000,
    category: 'OBC',
    aadhar: '9012 3456 7890',
  },
  {
    id: 'std-2009',
    rollNo: 'GSS-2026-001',
    name: 'Sunita Devi',
    school: 'GSS Diploma College',
    course: 'Diploma in Special Education (HI)',
    semester: 2,
    lateralEntry: false,
    admissionYear: '2025',
    dob: '14/07/1998',
    gender: 'Female',
    guardianName: 'Rajendra Prasad',
    phone: '9109876543',
    address: 'Gram Devpura, Sonbhadra, UP',
    feeStatus: 'Paid',
    totalFees: 40000,
    paidFees: 40000,
    category: 'SC',
    aadhar: '0123 4567 8901',
  },
  {
    id: 'std-2010',
    rollNo: 'GSS-2026-002',
    name: 'Manoj Tiwari',
    school: 'GSS Diploma College',
    course: 'Diploma in Special Education (MR)',
    semester: 1,
    lateralEntry: false,
    admissionYear: '2026',
    dob: '30/05/1999',
    gender: 'Male',
    guardianName: 'Kailash Tiwari',
    phone: '9098765432',
    address: 'Colony Tiwari Niwas, Gorakhpur, UP',
    feeStatus: 'Pending',
    totalFees: 40000,
    paidFees: 0,
    category: 'General',
    aadhar: '1234 5678 9012',
  },
  {
    id: 'std-2011',
    rollNo: 'RGP-2026-005',
    name: 'Deepak Rajbhar',
    school: 'Rajiv Gandhi Polytechnic',
    course: 'Mechanical Engineering',
    semester: 5,
    lateralEntry: false,
    admissionYear: '2023',
    dob: '11/02/2003',
    gender: 'Male',
    guardianName: 'Ramadhar Rajbhar',
    phone: '8987654321',
    address: 'Village Durgapur, Ballia, UP',
    feeStatus: 'Overdue',
    totalFees: 20000,
    paidFees: 5000,
    category: 'OBC',
    aadhar: '2345 6780 1234',
  },
  {
    id: 'std-2012',
    rollNo: 'ITI-2026-005',
    name: 'Kavita Chauhan',
    school: 'Rajiv Gandhi ITI',
    course: 'Electrician',
    semester: 2,
    lateralEntry: false,
    admissionYear: '2025',
    dob: '25/10/2005',
    gender: 'Female',
    guardianName: 'Shambhu Chauhan',
    phone: '8876543210',
    address: 'Mohalla Chauhan Tola, Deoria, UP',
    feeStatus: 'Paid',
    totalFees: 15000,
    paidFees: 15000,
    category: 'General',
    aadhar: '3456 7801 2345',
  },
];